/**
 * ERSTopupService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package net.symbiosis.core.integration.voucher.glo.seamless;

public interface ERSTopupService extends java.rmi.Remote {
    public ERSWSResponse customOperation(ClientContext clientContext, PrincipalId customerPrincipalId, PrincipalId targetPrincipalId, net.symbiosis.core.integration.voucher.glo.seamless.PrincipalAccountSpecifier senderAccountSpecifier, String operationId, ErsMap operationParameters) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSDeLinkSubResellerResponse deLinkSubReseller(ClientContext context, String parentResellerId, PrincipalId principalId) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSRegisterSubResellerResponse registerSubReseller(ClientContext context, String resellerId, String resellerMsisdn, String resellerType, String parentResellerId, String firstName, String lastName, String defaultPin) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.CommitTopupResponse commitTopup(ClientContext context, PrincipalId senderPrincipalId, PrincipalId topupPrincipalId, net.symbiosis.core.integration.voucher.glo.seamless.PrincipalAccountSpecifier senderAccountSpecifier, net.symbiosis.core.integration.voucher.glo.seamless.PrincipalAccountSpecifier topupAccountSpecifier, Amount topupAmount, String ersReference, String reasonCode, String comment, boolean fetchsubscriberBalance) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSGetTransactionStatusResponse getTransactionStatus(ClientContext context, PrincipalId resellerPrincipalId) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSPrincipalInformationResponse requestPrincipalInformation(ClientContext context, PrincipalId principalId, String nativeReslutCode) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSTopupResponse requestTopup(ClientContext context, PrincipalId senderPrincipalId, PrincipalId topupPrincipalId, net.symbiosis.core.integration.voucher.glo.seamless.PrincipalAccountSpecifier senderAccountSpecifier, net.symbiosis.core.integration.voucher.glo.seamless.PrincipalAccountSpecifier topupAccountSpecifier, String productId, Amount amount) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSTransferResponse requestTransfer(ClientContext context, PrincipalId senderPrincipalId, PrincipalId receiverPrincipalId, net.symbiosis.core.integration.voucher.glo.seamless.PrincipalAccountSpecifier senderAccountSpecifier, net.symbiosis.core.integration.voucher.glo.seamless.PrincipalAccountSpecifier receiverAccountSpecifier, String productId, Amount amount) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSCancelPurchaseResponse cancelPurchase(ClientContext context, net.symbiosis.core.integration.voucher.glo.seamless.CancelPurchaseOrderRow[] cancelPurchaseOrder) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSUnFreezeResellerResponse unFreezeReseller(ClientContext context, net.symbiosis.core.integration.voucher.glo.seamless.TargetPrincipal targetReseller) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSFreezeResellerResponse freezeReseller(ClientContext context, net.symbiosis.core.integration.voucher.glo.seamless.TargetPrincipal targetReseller) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSLinkSubResellerResponse linkSubReseller(ClientContext context, String parentResellerId, PrincipalId principalId) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSUnBlockResellerResponse unBlockReseller(ClientContext context, net.symbiosis.core.integration.voucher.glo.seamless.TargetPrincipal targetReseller) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSGetVouchersDenominationResponse getVouchersDenomination(ClientContext context) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSPurchaseResponse requestPurchase(ClientContext context, PrincipalId senderPrincipalId, PrincipalId receiverPrincipalId, net.symbiosis.core.integration.voucher.glo.seamless.PrincipalAccountSpecifier senderAccountSpecifier, net.symbiosis.core.integration.voucher.glo.seamless.PrincipalAccountSpecifier receiverAccountSpecifier, net.symbiosis.core.integration.voucher.glo.seamless.PurchaseOrderRow[] purchaseOrder, Entry[] extraFields) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSTopupResponse redeemVoucher(Parameter[] transactionProperties, String voucherSerial, String voucherVerificationCode, PrincipalId topupPrincipalId, String sendSmsNotification) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.CancelTopupResponse cancelTopup(ClientContext context, PrincipalId senderPrincipalId, PrincipalId topupPrincipalId, net.symbiosis.core.integration.voucher.glo.seamless.PrincipalAccountSpecifier senderAccountSpecifier, net.symbiosis.core.integration.voucher.glo.seamless.PrincipalAccountSpecifier topupAccountSpecifier, String ersReference, String reasonCode, String comments) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSUpdateResellerResponse updateReseller(ClientContext context, net.symbiosis.core.integration.voucher.glo.seamless.TargetPrincipal targetReseller, net.symbiosis.core.integration.voucher.glo.seamless.UpdateResellerParams updateResellerProfile) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSDeActivateResellerResponse deActivateReseller(ClientContext context, net.symbiosis.core.integration.voucher.glo.seamless.TargetPrincipal targetReseller) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSActivateResellerResponse activateReseller(ClientContext context, String activationCode) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSExecuteReportResponse executeReport(ClientContext context, String reportId, String language, ParameterMap parameters) throws java.rmi.RemoteException;
    public net.symbiosis.core.integration.voucher.glo.seamless.ERSWSBlockResellerResponse blockReseller(ClientContext context, net.symbiosis.core.integration.voucher.glo.seamless.TargetPrincipal targetReseller) throws java.rmi.RemoteException;
    public ERSWSResponse changePrincipalPassword(ClientContext context, PrincipalId principalId, String newPassword) throws java.rmi.RemoteException;
}
